# Use a Maven image for running tests
FROM maven:3.9.4-eclipse-temurin-17 AS test-runner
WORKDIR /app

# Copy the source code
COPY . .

# Run the tests
CMD ["mvn", "test", "-Dmaven.surefire.debug", "-DargLine=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005"]
